#pragma once

#define MAGIC_CODE					0xB7E2
#define EX_MAGIC_CODE				0xC8F3 
#define MAX_MAINCMDNUMBER			3999
#define MAX_MAINCMDEXNUMBER			512
#define P_OK						0
#define P_FAIL						-1
#define P_ERROR						-1 //ErrorFuncTraceAndReturn(__FUNCTION__, __FILE__, __LINE__, 0) //gera log e desconecta

#define ALIAS_PTR(type, declare, value)				\
	type* declare (reinterpret_cast<type*>(value)); \
	if(!declare) { return P_ERROR; }

enum MAINCMD_VALUE_CUSTOM
{
	S2C_EVENT_ALERT,
	S2C_BM3MACRORESULT,
	C2S_WINDOWDETECTED
};

enum MAINCMD_VALUE_EX
{
	NFS_LASTERRCODE = 7,

	// --------------------------------------------------------------------
	MAINCMD_VALUE_EX_BEGIN = 100,
	ITC_MOBSMIGTION = 101,	
	ITC_MOBSDEADRTN = 102,	
	ITC_MOBSWARPRTN = 103,	
	ITC_REQSNAPSHOT = 104,	
	ITC_ACKSNAPSHOT = 105,	
	ITC_MIGRATIONS0 = 106,	
	ITC_ROUTEPACKET = 107,
	ITC_ROUTE2DBAGT = 108,
	ITC_RESULTSYSMG = 120,	
	ITC_RESULTVERFY = 121,	
	ITC_RESULTEMGTS = 122,	
	ITC_RESULTINITS = 123,	
	ITC_RESULTUNINT = 124,	
	ITC_RESULTGETWH = 125,	
	ITC_RESULTITEMD = 126,	
	ITC_RESULTITEMB = 127,	
	ITC_RESULTITEMP = 128,	
	ITC_RESULTGETCH = 130,	
	ITC_RESULTNEWCH = 131,	
	ITC_RESULTDELCH = 132,	
	CSC_GETMYCHARTR = 133,	
	CSC_NEWMYCHARTR = 134,	
	CSC_DELMYCHARTR = 135,	
	CSC_CONNECT2SVR = 140,	
	CSC_VERIFYLINKS = 141,	
	CSC_INITIALIZED = 142,	
	CSC_UNINITIALZE = 143,	
	CSC_GETLATENCYS = 144,	
	CSC_GETMYWAREHS = 145,	
	CSC_QUICKLNKSET = 146,	
	CSC_QUICKLNKXCH = 147,	
	CSC_GETSVRTIME = 148,	
	CSC_ITEMEQUIPS0 = 150,	
	CSC_ITEMXEQUIPS = 151,	
	CSC_ITEMUNEQUIP = 152,	
	CSC_ITEMLOOTING = 153,	
	CSC_ITEMLOOTIN2 = 154,	
	CSC_ITEMLOOTIN3 = 155,	
	CSC_ITEMLOOTIN4 = 156,	
	CSC_ITEMDROPING = 157,	
	CSC_ITEMHOLDING = 158,	
	CSC_ITEMPUTTING = 159,	
	CSC_ITEMXCHANGE = 160,	
	CSC_ITEMBUYINGS = 161,	
	CSC_ITEMSELLING = 162,	
	CSC_ITEMMERGING = 163,	
	CSC_ITEMDROPUSR = 164,  
	CSC_UNEQUIPHAND = 165,  
	CSC_WAREHHOLDNG = 170,	
	CSC_WAREHPUTTNG = 171,	
	CSC_WAREHXCHNGE = 172,	
	CSC_WAREHSAVING = 173,	
	CSC_SKILLTOMOBS = 174,	
	CSC_SKILLTOUSER = 175,	
	CSC_ATTCKTOMOBS = 176,	
	CSC_ATTCKTOUSER = 177,	
	CSC_PARTYINVITE = 180,	
	CSC_PARTYJOINME = 181,	
	CSC_PARTYEXIT00 = 182,	
	CSC_PARTYMEMBAN = 183,	
	CSC_PARTYCOMMSN = 184,	
	CSC_PARTYPROPRT = 185,	
	CSC_PARTYINVCCL = 186,	
	CSC_PARTYAUTHORITYCHANGE = 187,
	REQ_MOVEBEGINED = 190,	
	REQ_MOVEENDED00 = 191,	
	REQ_MOVECHAGNED = 192,	
	REQ_MOVEWAYPNTS = 193,	
	REQ_MOVETILEPOS = 194,	
	REQ_MESSAGEEVNT = 195,	
	REQ_PARTYINVITE = 196,	
	REQ_PARTYMESSAG = 197,	
	NFY_NEWUOBJLIST = 198,  
	NFY_DELUOBJLIST = 199,  
	NFY_NEWUSERLIST = 200,	
	NFY_DELUSERLIST = 201,	
	NFY_NEWMOBSLIST = 202,	
	NFY_DELMOBSLIST = 203,	
	NFY_NEWITEMLIST = 204,	
	NFY_DELITEMLIST = 205,	
	NFY_ITEMEQUIPS0 = 206,	
	NFY_ITEMUNEQUIP = 207,	
	NFY_MOVEBEGINED = 210,	
	NFY_MOVEENDED00 = 211,	
	NFY_MOVECHANGED = 212,	
	NFY_MOBSMOVEBGN = 213,	
	NFY_MOBSMOVEEND = 214,	
	NFY_MOBSCHASBGN = 215,	
	NFY_MOBSCHASEND = 216,	
	NFY_MESSAGEEVNT = 217,	
	NFY_SKILLTOMOBS = 220,	
	NFY_SKILLTOUSER = 221,	
	NFY_SKILLTOMTON = 222,	
	NFY_SKILLBYMOBS = 223,	
	NFY_SKILLBYMTON = 224,	
	NFY_ATTCKTOMOBS = 225,	
	NFY_ATTCKTOUSER = 226,	
	NFY_ATTCKMOTION = 227,	
	NFY_PARTYMEMSIN = 230,	
	NFY_PARTYMEMOUT = 231,	
	NFY_PARTYMEMBAN = 232,	
	NFY_PARTYCOMMSN = 233,	
	NFY_PARTYPROPRT = 234,	
	NFY_PARTYMEMWAP = 235,	
	NFY_PARTYMESSAG = 236,	
	NFY_PARTYMEMSTT = 237,	
	NFY_PARTYATTEXP = 238,	
	NFY_PARTYREJECT = 239,	
	NFY_PARTYINVCCL = 240,	
	NFY_SYSTEMMESSG = 241,	
	REQ_DISCONNECTS = 242,	
	NFY_SYSTEMDEBUG = 243,	
	CSC_WARPCOMMAND = 244,	
	ITC_RESULTWARPC = 245,	
	REQ_SKILLCHANGE = 246,	
	NFY_SKILLCHANGE = 247,	
	REQ_SKILLCHANG2 = 248,	
	CSC_USESTATBONS = 250,	
	REQ_USERFMTCST2 = 251,	
	REQ_USERFMTCST4 = 252,	
	NFY_USERFMTCST2 = 253,	
	NFY_USERFMTCST4 = 254,	
	REQ_TRADEREQUST = 260,	
	CSC_TRADEOPNEVT = 261,	
	CSC_TRADECLSEVT = 262,	
	NFY_TRADEEVENTS = 263,	
	CSC_TRADEADDITM = 264,	
	CSC_TRADEADDALZ = 265,	
	CSC_TRADERMVITM = 266,	
	NFY_TRADEADDITM = 267,	
	NFY_TRADERMVITM = 268,	
	REQ_TRADEREQLST = 269,	
	CSC_SKILLTRAINS = 270,	
	CSC_SKILLUTRAIN = 271,	
	CSC_AURAEXCHANG = 272,	
	CSC_COMBSKILSET = 273,	
	REQ_COMBSKEVENT = 274,	
	NFY_COMBSKEVENT = 275,	
	CSC_SMASTUPEVNT = 276,	
	CSC_ENCHANTCORE = 280,	
	CSC_EXTRACTCORE = 281,	
	CSC_QUESTOPNEVT = 282,	
	CSC_QUESTCLSEVT = 283,	
	CSC_QUESTCCLEVT = 284,	
	CSC_ITEMUSING00 = 285,	
	CSC_ITEMSPLITE = 286,  
	NFY_UPDATEDATAS = 287,	
	NFY_CHARTREVENT = 288,	
	CSC_QDUNGEONSTR = 290,	
	CSC_QDUNGEONEND = 291,	
	CSC_QDUNGEONMOA = 292,	
	CSC_QDOPENGATE0 = 293,	
	NFY_QDUNGEONEND = 294,
	NFY_QDUNGEONMAD = 300,	
	NFY_QDUNGEONSTR = 301,	
	NFY_QDCHGMISTAT = 302,	
	NFY_QDPPCOMPLET = 303,	
	NFY_RESERVERD01 = 304,
	NFY_RESERVED002 = 305,
	NFY_RESERVED003 = 306,
	NFY_RESERVED004 = 307,
	NFY_RESERVED005 = 308,
	REQ_SKILLTOACTS = 310,	
	NFY_SKILLTOACTS = 311,	
	CSC_BMODETOMOBS = 312,	
	CSC_BMODETOUSER = 313,	
	NFY_BMODETOMOBS = 314,	
	NFY_BMODETOUSER = 315,	
	NFY_BMODETOMTON = 316,	
	REQ_SKILLTOPREV = 317,	
	NFY_SKILLTOPREV = 318,	
	CSC_QSTNPCACTIN = 320,	
	CSC_ATTKBOSSMOB = 321,	
	CSC_CHANGESTYLE = 322,	
	NFY_CHANGESTYLE = 323,	
	CSC_CHARGEINFO = 324,	
	NFY_CHARGEINFO = 325,	
	CSC_PVPREQUEST = 330,
	NFY_PVPREQUEST = 331,
	CSC_PVPRESPONSE = 332,
	NFY_PVPRESPONSE = 333,
	CSC_PVPENDING = 334,
	NFY_PVPENDING = 335,
	CSC_PVPCANCEL = 336,
	NFY_PVPCANCEL = 337,
	REQ_PVPSTANDUP = 338,
	NFY_PVPSTANDUP = 339,
	NFY_PVPCHARINFO = 340,
	CSC_PKREQUEST = 341,
	NFY_PKREQUEST = 342,
	CSC_PKENDING = 343,
	NFY_PKENDING = 344,
	NFY_PKLEVCHANGE = 345,
	CSC_RPTCHANGE = 346,
	NFY_RPTCHANGE = 347,
	CSC_MULTITARGETUSER = 349,
	CSC_NEWTARGETUSER = 350,
	CSC_CHGTARGETUSER = 351,
	REQ_ENDTARGETUSER = 352,
	NFY_TARGETCHARINFO = 353,
	CSC_GUILDKILL = 354,
	NFY_GUILDKILL = 355,
	CSC_CHANGENATION = 356,
	NFY_CHANGENATION = 357,
	CSC_CENSUSNATION = 358,
	CSC_PSHOPOPEN = 360,
	NFY_PSHOPOPEN = 361,
	CSC_PSHOPCLOSE = 362,
	NFY_PSHOPCLOSE = 363,
	CSC_PSHOPVISIT = 364,
	CSC_PSHOPEXIT = 365,
	CSC_PSHOPSELL = 366,
	NFY_PSHOPSELL = 367,
	CSC_PSHOPBUY = 368,
	NFY_PSHOPBUY = 369,
	NFY_STOPBUFFING = 370,
	CSC_PARTYQUESTOPEN = 371,
	CSC_PARTYQUESTCLOSE = 372,
	CSC_PARTYQUESTNPCACTION = 373,
	CSC_PARTYQUESTITEMLOOTING = 374,
	NFY_PARTYQUESTOPEN = 375,
	NFY_PARTYQUESTCLOSE = 376,
	NFY_PARTYQUESTNPCACTION = 377,
	NFY_PARTYQUESTITEMLOOTING = 378,
	NFY_PARTYQUESTMMOBKILL = 379,
	CSC_PSHOPAUTOREGIST = 380,
	NFY_PSHOPAUTOREGIST = 381,
	NFY_SPECIALBUFFTOMOBS = 390,
	REQ_CHANGEDIRECTION = 391,
	NFY_CHANGEDIRECTION = 392,
	REQ_LOUDMSGCHANNEL = 393,
	NFY_LOUDMSG = 394,
	REQ_LOUDMSGSERVER = 395,
	REQ_LOUDMSGSERVER2 = 396,
	NFY_LOUDMSGREC = 397,
	REQ_KEYMOVEBEGINED = 401,
	REQ_KEYMOVEENDED00 = 402,
	NFY_KEYMOVEBEGINED = 403,
	NFY_KEYMOVEENDED00 = 404,
	REQ_KEYMOVECHANGED = 405,
	NFY_KEYMOVECHANGED = 406,
	CSC_ITEMMAKE = 410,
	CSC_ITEMDISINTEGRATE = 411,
	C2C_SPECIALBUFF = 412,
	NFY_SKILLBYMWIDE = 413,
	NFY_ITEMCREATED = 414,
	CSC_QUERYCASH = 416,
	CSC_BUYCASHITEM = 417,
	CSC_QUERYCASHITEM = 418,
	CSC_USECASHITEM = 419,
	CSC_HEARTBEAT = 420,
	CSC_CUSTOM_PACKET = 421,
	CSC_DESTROYCASHITEM = 422,
	NFY_DESTROYCASHITEM = 423,
	NFY_USERENAMEDCARD = 424,
	NFY_ADDBLESSINGBEAD = 425,
	NFY_USECHARACTERFX = 426,
	NFY_USECHANGEKIT = 427,
	CSC_MAIL = 430,
	CSC_QUERYMAIL = 431,
	CSC_READMAIL = 432,
	CSC_SENDMAIL = 433,
	CSC_DELETEMAIL = 434,
	CSC_USEMAILITEM = 435,
	NFY_RCVMAIL = 436,
	CSC_RCVMAILALZ = 437,

#ifdef CARRIAGE_FORWARD_MAIL
	CSC_SENDRETURNMAIL = 438,
#endif // CARRIAGE_FORWARD_MAIL

	NFY_RESURRECTION = 440, 
	CSC_RESURRECTION = 441, 
	NFY_ITEMAVATAREQUIP = 443,
	NFY_ITEMAVATARUNEQUIP = 444,
	CSC_GUILDINFOINIT = 445,
	CSC_GWREQUEST = 446,
	CSC_GWREQRESULT = 447,
	CSC_GWRESPONSE = 448,
	CSC_GWMYGMAGREE = 449,
	CSC_GWOPGMAGREE = 450,
	CSC_GWJOIN = 451,
	NFY_GWSTART = 452,
	NFY_GWENDING = 453,
	CSC_GWCANCEL = 454,
	CSC_GWCANCELRESULT = 455,
	NFY_ITEMBALLOONEQUIP = 460,
	NFY_ITEMBALLOONUNEQUIP = 461,	
	NFY_SPECIALBUFFTOUSER = 462,
	ITC_RESULTLOUDMSG = 463,
	CSC_SERVERENV = 464,
	NFY_BTMODERR = 465,
	NFY_REMOVEUNSAVEITEM = 466,
#ifdef USE_AUTOBLOCK
	REQ_BLOCKAUTOUSER = 467,  
#endif//USE_AUTOBLOCK
	CSC_GETTEMPINVEN = 469,

#ifdef APEX_V10
	CSC_APEXDATA = 470,
	ITC_APEXKICKOUT = 471,
#endif

#ifdef USE_XTRAP
	CSC_XTRAPAUTH = 475,
	CSC_XTRAPDETECTCRACK = 476,
#endif

#ifdef EST_PCBANG
	CSC_ESTPCBANGALERT = 480,
	CSC_ESTPCBANGEXPIRED = 481,
	NFY_ESTPCBANGPOINT = 482,
#endif

	//ÀÎ´ø¼ö Ã¼Å© ÆÐÅ¶
	C2S_SENDPMMESSAGE = 483,
	CSC_QDLIMITCHECK = 485,

	CSC_GENDERCHANGE = 488,
	CSC_ACSYITEMXEQUIT = 486,

	CSC_GMCOMMAND = 490,
	NFY_CHANGEGMFLAG = 491,
	NFY_BLOCKUSER = 492,

	CSC_GUILDCREATEFEE = 496,

#ifdef USE_GUILD_RENAME_CARD
	//	CSC_GUILDNAMECHANGEFEE = 497,
	CSC_GUILDNAMECHANGENOTIFY = 498,
#endif

	CSC_NOTIFYINSTANTPLAYTIME = 505,

#ifdef __TESTEX__//µð¹ö±×¿ë
	CSC_GETMOBSTATUS = 510,
#endif

	CSC_CUSTOMPACKETMAIN = 545,
	CSC_IWAR_PARTYLETMEJOIN = 550,
	CSC_IWAR_PARTYLETMEJOINRESULT = 551,
	CSC_IWAR_PARTYLETMEJOINCANCEL = 552,

	CSC_IWAR_NOTIFYSVRSHUTDOWNELAPSEDTIME = 599,
	CSC_IWAR_NOTIFYLOBBYELAPSEDTIME = 600,
	CSC_IWAR_NOTIFYLOBBYEND = 601,
	CSC_IWAR_NOTIFYBFELAPSEDTIME = 602,
	CSC_IWAR_NOTIFYBFEND = 603,
	CSC_IWAR_NOTIFYUSERWORLDINOUT = 604,
	CSC_IWAR_NATIONMEMBERLIST = 605,
	CSC_IWAR_NOTIFYLOBBYENDINCOMING = 606,
	CSC_IWAR_NOTIFYUSERPARTYSTATE = 607,
	CSC_IWAR_NOTIFYBFSTART = 608,
	CSC_IWAR_MOVETOBF = 609,
	CSC_IWAR_NOTIFYBFENTRYAVAILABLE = 610,
	CSC_IWAR_NOTIFYENTRYORDERUPDATED = 611,
	CSC_IWAR_NOTIFYWARSCORECHANGED = 612,
	CSC_IWAR_NOTIFYWARPOINTCHANGED = 613,
	CSC_IWAR_NOTIFYALZIO = 614,
	CSC_IWAR_NOTIFYWAREND = 615,
	CSC_IWAR_INDIVIDUALREWARD = 616,
	CSC_IWAR_SELECTINDIVIDUALREWARD = 617,
	CSC_IWAR_NOTIFYINDIVIDUALREWARDITEMLIST = 618,
	CSC_IWAR_NOTIFYUSERKILLDEAD = 619,
	CSC_IWAR_NOTIFYMAXENTRYLIMITPERNATION = 620,
	CSC_IWAR_NOTIFYLASTNATIONREWARDWARRESULTS = 621,
	C2C_IWAR_NOTIFYEXPBYTARGETKILL = 622,
	CSC_IWAR_NOTIFYUSERWARSTATISTICS = 623,

	//////////////////////////////////////////////////////////////////////////
	// War Object
	//////////////////////////////////////////////////////////////////////////
	// Legacy
	NFY_IWAR_NEWFORTRESSLIST = 650,  // NFS_IWAR_NEWFORTRESSLIST
	CSC_IWAR_TAKELEGACYCORE = 651,  // C2S_IWAR_TAKELEGACYCORE, S2C_IWAR_TAKELEGACYCORE
	CSC_IWAR_MAKELEGACYBARRIER = 652,  // C2S_IWAR_MAKELEGACYBARRIER, S2C_IWAR_MAKELEGACYBARRIER
	CSC_IWAR_MAKELEGACYGUARDIAN = 653,  // C2S_IWAR_MAKELEGACYGUARDIAN, S2C_IWAR_MAKELEGACYGUARDIAN
	CSC_IWAR_FORTRESSUNDERATTACK = 654,  // C2S_IWAR_FORTRESSUNDERATTACK, S2C_IWAR_FORTRESSUNDERATTACK
	NFY_IWAR_FORTRESSUNDERATTACK = 655,  // NFS_IWAR_FORTRESSUNDERATTACK

	//////////////////////////////////////////////////////////////////////////
	// User Object
	//////////////////////////////////////////////////////////////////////////
	CSC_IWAR_MAKEFORCETOWERBYNPC = 660,  // C2S_IWAR_MAKEFORCETOWERBYNPC, S2C_IWAR_MAKEFORCETOWERBYNPC
	CSC_IWAR_MAKEFORCETOWERBYITEM = 661,  // C2S_IWAR_MAKEFORCETOWERBYITEM, S2C_IWAR_MAKEFORCETOWERBYITEM
	NFY_IWAR_FINISHFORCETOWER = 662,  // NFS_IWAR_FINISHFORCETOWER

	CSC_IWAR_REPAIRFORCETOWER = 663,  // C2S_IWAR_REPAIRFORCETOWER, S2C_IWAR_REPAIRFORCETOWER
	NFY_IWAR_REPAIRFORCETOWER = 664,  // NFS_IWAR_REPAIRFORCETOWER
	NFY_IWAR_REPAIRFORCETOWER_OWNER = 665,  // NFS_IWAR_REPAIRFORCETOWER_OWNER

	CSC_IWAR_CANCELFORCETOWER = 666,  // C2S_IWAR_CANCELFORCETOWER, S2C_IWAR_CANCELFORCETOWER
	NFY_IWAR_CANCELFORCETOWER = 667,  // NFS_IWAR_CANCELFORCETOWER

	NFY_IWAR_NEWFORCETOWERLIST = 668,  // NFS_IWAR_NEWFORCETOWERLIST
	NFY_IWAR_DELFORCETOWERLIST = 669,  // NFS_IWAR_DELFORCETOWERLIST

	CSC_IWAR_USEWARPFORCETOWER = 670,  // C2S_IWAR_USEWARPFORCETOWER, S2C_IWAR_USEWARPFORCETOWER
	CSC_IWAR_USERELIVEFORCETOWER = 671,  // C2S_IWAR_USERELIVEFORCETOWER, S2C_IWAR_USERELIVEFORCETOWER
	NFY_IWAR_WARPTOFORCETOWER = 672,  // NFS_IWAR_WARPTOFORCETOWER

	NFY_IWAR_CONTROLPANELLIST = 673,  // NFS_IWAR_CONTROLPANELLIST

	NFY_IWAR_DEFAULTWARMAPINFO = 674,  // NFS_IWAR_DEFAULTWARMAPINFO
	NFY_IWAR_FORCETOWERSCORE = 675,
	NFY_IWAR_ENTRY = 681,

#ifdef USE_BAN_SLEEP_USER
	NFY_IWAR_YELLOWALERT = 677,
	NFY_IWAR_REDALERT = 678,
#endif


	//////////////////////////////////////////////////////////////////////////
	/* 701 ~ 715  new skill/buff reserved */
	CSC_SKILLTOTARGET = 701,
	NFY_SKILLTOTARGET = 702,

	CSC_BASICBUFF = 703,	// C2S_BASICBUFFF, S2C_BASICBUFFF
	NFY_BASICBUFF = 704,  // NFS_BASICBUFF

	CSC_SCOPEBUFF = 705,	// S2C_SCOPEBUFF
	NFY_SCOPEBUFF = 706,	// NFS_SCOPEBUFF

	CSC_PARTYBUFF = 707,	// C2S_PARTYBUFF, S2C_PARTYBUFF
	NFY_PARTYBUFF = 708,	// NFS_PARTYBUFF

	CSC_NATIONBUFF = 709,	// TODO: C2S_NATION,S2C_NATION
	NFY_NATIONBUFF = 710,	// TODO: NFS_NATION

	// NPC : ForceTower, Monster
	NFY_ATTACKFROMNPC = 711,	// NFS_ATTACKFROMNPC
	NFY_BUFFFROMNPC = 712,	// NFS_BUFFFROMNPC
	NFY_BUFFFEND = 713,	// NFS_ENDBUFF

	NFY_ENERVATIONVALUE = 714,

	//////////////////////////////////////////////////////////////////////////
	/* 716 ~ 723  new skill/heal reserved */
	CSC_BASICHEAL = 716,	// C2S_BASICHEAL, S2C_BASICHEAL
	NFY_BASICHEAL = 717,  // NFS_BASICHEAL

	CSC_SCOPEHEAL = 718,	// S2C_SCOPEHEAL
	NFY_SCOPEHEAL = 719,	// NFS_SCOPEHEAL

	CSC_PARTYHEAL = 720,	// C2S_PARTYHEAL, S2C_PARTYHEAL
	NFY_PARTYHEAL = 721,	// NFS_PARTYHEAL	

	CSC_NATIONHEAL = 722,
	NFY_NATIONHEAL = 723,
	//////////////////////////////////////////////////////////////////////////

	CSC_WAREXP_EXCHANGE = 750,
#ifdef USE_NOTIFY_SKILL_STATUS
	CSC_NOTIFY_SKILL_STATUS = 760,
#endif

	CSC_CHECKUSERPRIVACYDATA = 800,
	CSC_ANTIONLINEGAMEBYPASS = 801,
	ITC_RESETINSTANTPLAYTIME = 802,

	CSC_BUFFREMOVEBLESSSELF = 803,

	CSC_TITLE_SHOWTITLE = 804,
	NFY_TITLE_SHOWTITLE = 805,
	CSC_TITLE_NEWTITLE = 806,
	CSC_TITLE_LOSETITLE = 807,
	NFY_TITLE_LOSETITLE = 808,
	CSC_TITLE_EQUIPTITLE = 809,
	NFY_TITLE_EQUIPTITLE = 810,
	CSC_TITLE_UNEQUIPTITLE = 811,
	NFY_TITLE_UNEQUIPTITLE = 812,

	NFY_LIVESTYLECHANGED = 850,

	NFY_IWAR_USERCOUNT = 899,

	NFY_RANDOM_VALUE = 901,
	REQ_TRIGGER_ACTION_NPC = 902,
	NFY_ATKSIGBYMOBS = 903,

#ifdef USE_GM_SHOW_CHARACTER_PARAMETERS_IN_CLIENT
	NFY_CHARACTER_PARAMETERS = 904,
#endif

#ifdef USE_PET_SYSTEMEX
	CSC_PETINFO = 905,
	NFY_PET_EXPINFO = 906,
	NFY_PET_LEVELUP = 907,

	CSC_ITU_PETOPTIONCLEAR = 908,
	NFY_PET_NICKNAME = 909,
	ITC_PET_RECIVED = 910,
	ITC_PET_NICKNAME = 911,
#endif

	NFY_ODDCIRCLE_USAGE = 912,

	CSC_UPPERGRADECOREENCHANT = 950,
	CSC_REQ_UPPERGRADECOREENCHANT2 = 951,

	ITC_TITLE_ADDRESULT = 960,
	ITC_TITLE_DELETERESULT = 961,
	CSC_APPOINT_INSTANCELORD = 995,
	CSC_REQCHARSELECTION_SCREEN = 985,
	MAINCMD_VALUE_EX_END = 1023,
	ON_REQENTRYWORLD = 1032,
	ITC_USERPOSDATA_COPY_REQ = 1069,
	C2S_PARTYACCEPT = 2011,
	CSC_ACCEPTPARTY = 2013, //ao clicar em sim ou não na PT
	CSC_ENDPARTY = 2019, //ao clicar em sim ou não na PT
	CSC_ENDPARTY2 = 2171, //ao clicar em sim ou não na PT
	CSC_NEW_PARTYMEMBER_DUNGEONCHECK = 2029,

	CSC_HPMP_ONLOGON = 2110,
	NFY_UPDATESPEED = 2111,
	CSC_CHANNEL_LIST = 2112,
	CSC_ENTRYDUNGEON_INFORMATIONS = 2029,
	NFY_DROPITEMLOOTING = 2036,
	eC2S_LOTTERY_ITEM = 2037,
	C2S_CONNECT_OTHERCHANNEL = 2141,
	REGISTER_MERCENARY = 2142,
	SUMMON_MERCENARY = 2143,
	CSC_ITEMEQUIP = 2165,
	CSC_ITEMSWITCH = 2166,
	S2CUPDATE_ITEM = 2170,
	CSC_DISCONNECT = 2173
};

enum SYSCMD_VALUE
{
	// --------------------------------------------------------------------
	SYSCMD_VALUE_BEGIN = 0,
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_LINK_TO_PROCESSLAYER_BEGIN
	ITC_LINK2PSLAYR = 1,	// ITS_LINK2PSLAYR
	ITC_ULNK2PSLAYR = 2,	// ITS_ULNK2PSLAYR
	// FOR_LINK_TO_PROCESSLAYER_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_MULTI_TIMER_BEGIN
	ITC_TIMERINTRPT = 3,	// ITS_TIMERINTRPT
	// FOR_MULTI_TIMER_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_REQUEST_TO_PROCESSLAYER_BEGIN
	ITC_REQSTINTRPT = 4,	// ITS_REQSTINTRPT
	// FOR_REQUEST_TO_PROCESSLAYER_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_SERVER_FAMILY_CONNECTION_BEGIN
	IPC_CONNECT2SVR = 5,	// IPS_CONNECT2SVR
	IPC_ACK4CONNECT = 6,	// IPS_ACK4CONNECT
	// FOR_SERVER_FAMILY_CONNECTION_END
	// --------------------------------------------------------------------

	NFY_LASTERRCODE = 7,

	// --------------------------------------------------------------------
	// MAINCMD_EXTEND_BEGIN
	SYS_MAINCMDEXTD = 10,
	// MAINCMD_EXTEND_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	SYSCMD_VALUE_END = 20
	// --------------------------------------------------------------------
};

enum MAINCMD_VALUE
{
	// --------------------------------------------------------------------
	MAINCMD_VALUE_BEGIN = SYSCMD_VALUE_END,
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_SYSTEM_MESSAGE_BEGIN
	IPC_SYSTEMMESSG = 21,	// IPS_SYSTEMMESSG
	IPC_RESULTSYSMG = 22,	// IPS_RESULTSYSMG
	// FOR_SYSTEM_MESSAGE_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_VERIFY_BEGIN
	IPC_VERIFYLINKS = 23,	// IPS_VERIFYLINKS
	IPC_RESULTVERFY = 24,	// IPS_RESULTVERFY
	// FOR_VERIFY_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_SERVER_FAMILY_RELAY/ROUTE_BEGIN
	IPC_RELAYPACKET = 25,
	IPC_ROUTEPACKET = 26,
	IPC_ROUTE2DBAGT = 27,
	// FOR_SERVER_FAMILY_RELAY/ROUTE_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_SETLOGIN_STATUS_BEGIN
	IPC_SETLOGINSTT = 28,	// IPS_SETLOGINSTT
	// FOR_SETLOGIN_STATUS_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_AUTH_BEGIN
	IPC_AUTHACCOUNT = 30,	// IPS_AUTHACCOUNT
	IPC_RESULTAUTHS = 31,	// IPS_RESULTAUTHS
	// FOR_AUTH_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_CHARACTER_BEGIN
	IPC_GETMYCHARTR = 32,	// IPS_GETMYCHARTR
	IPC_RESULTGETCH = 33,	// IPS_RESULTGETCH

	IPC_NEWMYCHARTR = 34,	// IPS_NEWMYCHARTR
	IPC_RESULTNEWCH = 35,	// IPS_RESULTNEWCH

	IPC_DELMYCHARTR = 36,	// IPS_DELMYCHARTR
	IPC_RESULTDELCH = 37,	// IPS_RESULTDELCH
	// FOR_CHARACTER_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_INITIALIZE_BEGIN
	IPC_INITIALIZED = 40,	// IPS_INITIALIZED
	IPC_RESULTINITS = 41,	// IPS_RESULTINITS
	// FOR_INITIALIZE_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_UNINITIALIZE_BEGIN
	IPC_UNINITIALZE = 42,	// IPS_UNINITIALZE
	IPC_RESULTUNINT = 43,	// IPS_RESULTUNINT
	// FOR_UNINITIALIZE_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_WAREHOUSE_BEGIN
	IPC_GETMYWAREHS = 44,	// IPS_GETMYWAREHS
	IPC_RESULTGETWH = 45,	// IPS_RESULTGETWH
	// FOR_WAREHOUSE_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_UPDATE_CHARACTER_DATA_BEGIN
	IPC_UPDATECHDAT = 46,	// IPS_UPDATECHDAT
	// FOR_UPDATE_CHARACTER_DATA_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	// FOR_ITEMSERIAL_BEGIN
	IPC_ITEMSERIAL0 = 50,	// IPS_ITEMSERIAL0
	IPC_RESULTITEMS = 51,	// IPS_RESULTITEMS
	// FOR_ITEMSERIAL_END
	// --------------------------------------------------------------------

	// --------------------------------------------------------------------
	IPC_NFYUSERCNT0 = 52,
	IPC_SERVERSTATE = 53,
	// --------------------------------------------

	// --------------------------------------------------------------------
	IPC_LOUDMESSAGE = 55,
	IPC_LOUDMSGERESULT = 56,
	// --------------------------------------------

	// --------------------------------------------
	IPC_CENSUSNATION = 57,
	IPC_RESULTCENSUS = 58,
	// --------------------------------------------

	// PCBang
	IPC_PCBANG_BILL = 60,
	IPC_PCBANG_BILLRET = 61,
	IPC_PCBANG_NOTICE = 62,
	IPC_PCBANG_CUTIP = 63,

	// Cash Item
	IPC_QUERYCASH = 66,
	IPC_RESULTCASH = 67,
	IPC_BUYCASHITEM = 68,
	IPC_RESULTBUYITEM = 69,
	IPC_QUERYCASHITEM = 70,
	IPC_RESULTQUERYITEM = 71,
	IPC_USECASHITEM = 72,
	IPC_RESULTUSEITEM = 73,
	IPC_RECOVERUSECASHITEM = 74,

	IPC_RENAMEDCARD = 75,
	IPC_BLOCKREQUEST = 76,
	IPC_BLOCKRESULT = 77,

	IPC_GETACCOUNTINFO = 78,

#ifdef USE_AUTOBLOCK
	IPC_BLOCKAUTOUSER = 79,
#endif//USE_AUTOBLOCK

	//Chat
	//gms¿¡ ÀÚ½Å(chatnode, chatcenter)ÀÇ Á¤º¸(ip, port, chatsvrindex)¸¦ µî·ÏÇÏµµ·Ï ¿äÃ»

	IPC_REGISTERCHATSVR = 80,

	//gms¿¡ chatnode, chatcenter°¡ ¿¬°áµÇ¸é ÇØ´ç Á¤º¸¸¦ ÀüÃ¼ chatnode, chatcenter¿¡ ¾Ë¸°´Ù.
	IPC_CHATNOTIFYSVRSTATE = 81,

	IPC_GUILDWARGETMEMBERLIST = 82,
	IPC_GUILDWARGETMEMBERLISTRESULT = 83,
	IPC_GUILDMASTERCHANGENOTIFY = 84,


	IPC_GUILDEMBLEMREGISTER = 85,
	IPC_GUILDEMBLEMREGISTERRESULT = 86,

	IPC_CHANGENATION = 87,

	IPC_NOTIFYGUILDEMBLEMREGIST = 88,

	IPC_BBEADPCBANGPOINTADD = 89,

	IPC_ESTPCBANGLOGIN = 90,
	IPC_ESTPCBANGLOGOUT = 91,
	IPC_ESTPCBANGCHARGE = 92,

	IPC_HACKUSERDBSAVE = 93,

	IPC_CHARDELETEDNOTIFY = 95,
	IPC_CHARCREATEDNOTIFY = 96,

#ifdef USE_EVENTDUNGEON
	IPC_EVENTDUNGEON = 97,
#else
	IPC_GENDERCHANGE = 97,
#endif //USE_EVENTDUNGEON

	IPC_CHANGESERVERSTATE = 98,
	IPC_CHANGECHANNELTYPE = 99,

	// --------------------------------------------------------------------
	MAINCMD_VALUE_END = 100
	//MAINCMD_VALUE_EX::CSC_CONNECT2SVR = 150,
	// --------------------------------------------------------------------
//#endif
};

enum eMAINCMD_VALUE
{
	MAINCMD_CUSTOM_IPC = 610,
	MAINCMD_CUSTOM = 3000
};

enum eMAINCMDIPC_VALUE_EX
{
	e_DEFAULT_MAINCMDIPC_EX = 0,
	IPC_EVENT_ALERT
};
